---
image: docker:20.10.2

services:
  - docker:20.10.2-dind

#
# Pipeline cache is based on CI_COMMIT_REF_SLUG.
#
cache:
  key: ${CI_COMMIT_REF_SLUG}

#
# Docker variables for allowing image build.
#
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  GIT_SUBMODULE_STRATEGY: recursive

#
# Workflow defining rules for running the pipeline.
# In the following cases the pipeline is not run when:
#  - the associated commit includes the work-in-progress tag `-wip`
#  - the associated commit message includes the pattern `Merge tag`: the commit resulting when
#    a release branch is closed and merged into `develop`
#
workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-wip/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /Merge tag/
      when: never
    - when: always

before_script:
  # Install required apk packages.
  - apk add --update bash wget ca-certificates openssl git tar openssh-client curl python3

#
# Extendable stages.
#
.common-production:
  only:
    - tags

.common-staging:
  only:
    - develop

.common-issue:
  only:
    - /^feature.*$/i
    - /^hotfix.*$/i
    - /^milestone.*$/i

#
# Static script to be reused by the enabled stages.
#

# Script for docker based stages.
.docker-script: &docker-script
  - docker login docker.io -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD

# Scripts for installing Ansible and the associated roles directly from the Lab.
.ansible-script: &ansible-script
  # Install and run ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use an RPM-based image)
  - 'which ssh-agent || apk add openssh-client'
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  # We're using tr to fix line endings which makes ed25519 keys work
  # without extra base64 encoding.
  # https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556

  # Configure .ssh folder
  - mkdir -p ~/.ssh
  - ssh-keyscan -p 4422 lab.u-hopper.com >> gitlabKey
  - ssh-keygen -lf gitlabKey
  - cat gitlabKey  >> ~/.ssh/known_hosts
  - chmod 700 ~/.ssh

  - apk add --update ansible ansible-lint

# Scripts for allowing the build of php/yii2 projects
# that require composer for installing dependencies.
.php-script: &php-script
  - apk add --update php7 php7-phar php7-json php7-iconv php7-openssl
  - curl --show-error --silent https://getcomposer.org/installer | php

# Script for allowing the connection to a remote server for completing a deployment.
.remote-server-connection: &remote-server-connection
  # Configure .ssh folder
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  # The USER_DEPLOY_SSH_KEY contains the private key granting access to the deployment server
  - echo "$USER_DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 400  ~/.ssh/id_rsa
  - export ANSIBLE_HOST_KEY_CHECKING=False

#
# Stages to run.
#
stages:
  - build
  - test
  - push
  - trigger
  - notify

#
# Build stages.
#

build_production:
  stage: build
  script:
    - *docker-script
    - ./docker-support/runner.sh -bs $CI_COMMIT_TAG
  artifacts:
    paths:
      - docker_image.tar.gz
    expire_in: 1 day
  extends: .common-production

build_staging:
  stage: build
  script:
    - *docker-script
    - ./docker-support/runner.sh -bs latest
  artifacts:
    paths:
      - docker_image.tar.gz
    expire_in: 1 day
  extends: .common-staging

build_issue:
  stage: build
  script:
    - *docker-script
    - ./docker-support/runner.sh -bs latest
  artifacts:
    paths:
      - docker_image.tar.gz
    expire_in: 1 day
  when: manual
  allow_failure: false
  extends: .common-issue


#
# Test stages
# Only configured for python projects. Currently there is not test support
# for php/yii2 projects.
#

test_production:
  stage: test
  script:
    - docker load -i docker_image.tar.gz
    - ./docker-support/runner.sh -t $CI_COMMIT_TAG
  dependencies:
    - build_production
  extends: .common-production

test_staging:
  stage: test
  script:
    - docker load -i docker_image.tar.gz
    - ./docker-support/runner.sh -t latest
  dependencies:
    - build_staging
  extends: .common-staging

test_issue:
  stage: test
  script:
    - docker load -i docker_image.tar.gz
    - ./docker-support/runner.sh -t latest
  dependencies:
    - build_issue
  allow_failure: false
  extends: .common-issue


#
# Push stages.
#

push_production:
  stage: push
  script:
    - *docker-script
    - docker load -i docker_image.tar.gz
    - ./docker-support/runner.sh -p $CI_COMMIT_TAG
  dependencies:
    - build_production
    - test_production
  extends: .common-production
push_staging:
  stage: push
  script:
    - *docker-script
    - docker load -i docker_image.tar.gz
    - ./docker-support/runner.sh -p latest
  dependencies:
    - build_staging
    - test_staging
  extends: .common-staging
push_issue:
  stage: push
  script:
    - *docker-script
    - docker load -i docker_image.tar.gz
    - ./docker-support/runner.sh -p latest
  dependencies:
    - build_issue
    - test_issue
  allow_failure: false
  extends: .common-issue


#
# Trigger stages.
# Allowing to trigger the deployment in another repository.
#


trigger_staging:
  stage: trigger
  script:
    - *ansible-script
    - export GIT_REF="develop"
    - ansible-playbook ansible/trigger.yml
  dependencies:
    - build_staging
    - test_staging
    - push_staging
  allow_failure: false
  extends: .common-staging

trigger_issue:
  stage: trigger
  script:
    - *ansible-script
    - export GIT_REF="develop"
    - ansible-playbook ansible/trigger.yml
  dependencies:
    - build_issue
    - test_issue
    - push_issue
  allow_failure: false
  extends: .common-issue





#
# Notification stages.
#
notify_production:
  stage: notify
  script:
    - *ansible-script
    - export RELEASE_TAG="$CI_COMMIT_TAG"
    - export BUILD_ENVIRONMENT="production"
    - export WITH_DEPLOY="yes"
    - export DEPLOY_TRIGGERED="no"
    - ansible-playbook ansible/notify.yml
  dependencies:
    - build_production
    - test_production
    - push_production
  allow_failure: true
  extends: .common-production

notify_staging:
  stage: notify
  script:
    - *ansible-script
    - export RELEASE_TAG="latest"
    - export BUILD_ENVIRONMENT="staging"
    - export WITH_DEPLOY="yes"
    - export DEPLOY_TRIGGERED="yes"
    - ansible-playbook ansible/notify.yml
  dependencies:
    - build_staging
    - test_staging
    - push_staging
    - trigger_staging
  allow_failure: true
  extends: .common-staging

notify_issue:
  stage: notify
  script:
    - *ansible-script
    - export RELEASE_TAG="latest"
    - export BUILD_ENVIRONMENT="issue"
    - export WITH_DEPLOY="yes"
    - export DEPLOY_TRIGGERED="yes"
    - ansible-playbook ansible/notify.yml
  dependencies:
    - build_issue
    - test_issue
    - push_issue
    - trigger_issue
  allow_failure: true
  extends: .common-issue



