---

- name: Setup Python project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_path: .
    project_type: python
    project_features:
      - test
      - docker
      - ci_cd
    docker_python_image_base_image: public.registry.u-hopper.com/python:3.8
    project_python_test_folder: tests
    docker_image_name: internetofus/service-api
    docker_registry: docker.io
    docker_python_services:
      - name: ws
        main_module: wenet_service_api.api.main
        required_env_variables:
          - ${PROFILE_MANAGER_CONNECTOR_BASE_URL}
          - ${TASK_MANAGER_CONNECTOR_BASE_URL}
          - ${HUB_CONNECTOR_BASE_URL}
        gunicorn_app: service_api_app

    ci_environments:
      production:
        stages:
          - name: build
          - name: test
            in_docker: true #TODO disable when the issue https://lab.u-hopper.com/wenet/wenet-services/-/issues/41 is completed
          - name: test
            type: coverage
          - name: push
          - name: notify
      staging:
        stages:
          - name: build
            manual: true
          - name: test
            in_docker: true #TODO disable when the issue https://lab.u-hopper.com/wenet/wenet-services/-/issues/41 is completed
          - name: push
          - name: trigger
            manual: true
            git_ref: develop
      mr:
        stages:
          - name: build
          - name: test
            in_docker: true #TODO disable when the issue https://lab.u-hopper.com/wenet/wenet-services/-/issues/41 is completed
          - name: test
            type: coverage
      default:
        stages:
          - name: build
          - name: build
            type: badge
          - name: test
            type: coverage
            in_docker: true #TODO disable when the issue https://lab.u-hopper.com/wenet/wenet-services/-/issues/41 is completed

    project_python_submodules:
      - name: wenet-common-models
  roles:
    - uh.project-template
