---

- name: Setup Python project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_path: .
    project_features:
      - test
      - docker
      - ci_cd

    project_test_folder: tests
    docker_image_name: wenet/service-api
    docker_run_services:
      - name: ws
        main_module: wenet_service_api.api.main
        required_env_variables:
          - ${PROFILE_MANAGER_CONNECTOR_BASE_URL}
          - ${TASK_MANAGER_CONNECTOR_BASE_URL}
          - ${HUB_CONNECTOR_BASE_URL}
        gunicorn_app: service_api_app
    ci_stages:
      - build
      - test
      - push
      - deploy
      - notify
    ci_environments:
      - prod
      - dev
      - issue
    project_submodules:
      - name: wenet-common-models
  roles:
    - uh.project-template
