---

- name: Setup Python project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_path: .
    project_type: python
    project_features:
      - test
      - docker
      - ci_cd
    docker_python_image_base_image: public.registry.u-hopper.com/python:3.8
    project_python_test_folder: test
    docker_image_name: internetofus/service-api
    docker_registry: docker.io
    docker_python_services:
      - name: ws
        main_module: wenet_service_api.api.main
        required_env_variables:
          - ${PLATFORM_BASE_URL}
          - ${COMP_AUTH_KEY}
        gunicorn_app: service_api_app
        gunicorn_extra_args: --timeout 60 --graceful-timeout 60

    ci_environments:
      production:
        stages:
          - name: build
          - name: test
          - name: test
            type: coverage
          - name: push
          - name: notify
      staging:
        stages:
          - name: build
            manual: true
          - name: test
          - name: push
          - name: trigger
            manual: true
            git_ref: develop
      mr:
        stages:
          - name: test
          - name: test
            type: coverage
          - name: test
            allow_failure: false
            ignore: E501,W504,E241,F405
            type: lint
      default:
        stages:
          - name: build
            type: badge
          - name: test
            type: coverage
    project_python_submodules: []
  roles:
    - uh.project-template
