- hosts: deploy_target
  vars:
    dir: "{{ lookup('env','DEPLOYMENT_TEST_DIR') }}"
  tasks:

  - name: reset env file
    shell: git checkout .env
    args:
        chdir: "{{ dir }}"
  - name: "git pull"
    git:
        repo: "git@lab.u-hopper.com:wenet/wenet-deployment.git"
        dest: "{{ dir }}"
        version: "develop"
        accept_hostkey: yes
        key_file: /home/gitlab/.ssh/id_rsa

  - name: check env
    shell: python3 check_env.py -t templates -e .
    args:
        chdir: "{{ dir }}"

  - name: rewrite service-api version
    lineinfile:
        path: "{{ dir }}/.env"
        line: WENET_SERVICE_API_VERSION=latest
        regexp: "^WENET_SERVICE_API_VERSION=[a-zA-Z0-9.]*$"
  - name: rewrite hub version
    lineinfile:
        path: "{{ dir }}/.env"
        line: WENET_HUB_VERSION=latest
        regexp: "^WENET_HUB_VERSION=[a-zA-Z0-9.]*$"
  - name: rewrite dev env
    lineinfile:
        path: "{{ dir }}/.env"
        line: DEV_ENV=_dev
        regexp: "^DEV_ENV=[a-zA-Z0-9.]*$"
    
  - name: "pull"
    shell: docker-compose pull service-api
    args:
      chdir: "{{ dir }}"
  - name: "stop"
    shell: docker-compose stop service-api
    args:
      chdir: "{{ dir }}"
  - name: "remove"
    shell: docker-compose rm -vf service-api
    args:
      chdir: "{{ dir }}"
  - name: "up"
    shell: docker-compose up -d service-api
    args:
      chdir: "{{ dir }}"