---
- hosts: localhost
  vars:
    slack_token: "{{ lookup('env', 'SLACK_TOKEN') }}"
    # slack_channel: "{{ lookup('env', 'SLACK_CHANNEL') | default('#the-developers', True) }}"
    # slack_username: "{{ lookup('env', 'SLACK_USERNAME') | default('uhopper lab', True) }}"
    build_environment: "{{ lookup('env', 'BUILD_ENVIRONMENT') }}"
    release_tag: "{{ lookup('env', 'RELEASE_TAG') }}"
    project_id: "{{ lookup('env', 'CI_PROJECT_ID') }}"
    project_title: "{{ lookup('env', 'CI_PROJECT_TITLE') }}"
    project_url: "{{ lookup('env', 'CI_PROJECT_URL') }}"
    project_path: "{{ lookup('env', 'CI_PROJECT_PATH') }}"
    commit_message: "{{ lookup('env', 'CI_COMMIT_MESSAGE') }}"
    commit_ref: "{{ lookup('env', 'CI_COMMIT_REF_NAME') }}"

    deploy_triggered: "{{ lookup('env', 'DEPLOY_TRIGGERED') }}"

    commit_attachments:
      - color: "#2eb887"
        text: |-
          <{{ project_url }} | {{ project_path }}>
          - Ref: `{{ commit_ref }}` :point_right: {{ commit_message }}
          - Environment: `{{ build_environment }}`
          - Image version: `{{ release_tag }}`
    deploy_requested_attachments:
      - color: "#cb007d"
        text: "The deployment on the associated `develop` branch has been triggered :robot_face:"
    deploy_manual_attachments:
      - color: "#0099ff"
        text:  "If needed, the deployment must be manually run :wave:"
    attachments: "{{ commit_attachments + deploy_requested_attachments if deploy_triggered == 'yes' else commit_attachments + deploy_manual_attachments }}"

  tasks:
    - name: Notify pipeline success
      slack:
        token: "{{ slack_token }}"
        # username: "{{ slack_username }}"
        # channel: "{{ slack_channel }}"
        msg: "Pipeline succeeded :rocket:"
        attachments: "{{ attachments }}"
